### ISSUE TITLE
Add findChildElements mefod for elements

### ISSUE THREAD

**Issue by nkrivitsky** [aquality-automation/aquality-selenium-java#66]
Now it's impossible to check existing subElement without exception.
It has got workflow like get Xpath of the parent element, add Xpath of the child and search as new element on the page.

**Comment by mialeska** [comment]
This would be fixed with #75 (with release of version 2.0.0), taking advantage of ByChained locators (see implementation of findChildElement method in ElementFactory class of https://github.com/aquality-automation/aquality-selenium-core-java/blob/master/src/main/java/aquality/selenium/core/elements/ElementFactory.java).
This won't be fixed for any findElements methods (which are designed to find multiple elements), because they need to define an amount of element as well as unique locators for them.
